### ISSUE TITLE
Not quite as successful

### ISSUE THREAD

**Issue by JoSchmaltz** [kiwih/LedMatrix#1]
Ha - just stumbled across your blog and code. I carried home this LED baby about a year ago and after some research decided I will never make it work the way I want it, but your post gave me hope again. My sign actually works in demo mode (see the video) but I really want to drop the whole controller and replace it with a pi or an esp32 to control it....but I haven't even gotten close to figuring out how to connect the seemingly daisy chained boards. The power supply is separate and works fine. I tried to apply your reverse engineering process to this sign, but TBH your blog is above my pay grade. Any pointers where and how to start would be greatly appreciated!

https://photos.app.goo.gl/ho22Ybx2Qr9tW5gu8

**Comment by kiwih** [comment]
From the video of the sign running - the sign says it has a serial address. Might you try sending the messages to the controller board to see if it will listen to you? See if you can find the user manual for the overall product. In my case I didn't have that option as I had no controller board. If you work with the controller it might simplify the overall task!
